apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: app
  template: 
    metadata: 
      name: app-pod
      labels: 
        app: app
    spec: 
      containers:
        - name: app-container
          image: docker.io/neerajpolavarapu/timeapp
          imagePullPolicy: Always
          ports: 
            - containerPort: 5000
          # resources: 
          #   requests:
          #     memory: 20Mi
          #     cpu: 1
          #   limits:
          #     memory: 1Gi
          #     cpu: 3
      # imagePullSecrets:
      # - name: regcred
      