apiVersion: v1
kind: Pod
metadata:
  name: sps-auth-maayaverse-fd9c45d7-vnsq8
  namespace: tenant-74334f-oidev
  labels:
    sps.tensorworks.com.au/auth: maayaverse
spec:
  containers:
    - name: sps-auth-container
      image: docker.io/tensorworks/sps-auth-plugin-noop:v0.9.10-coreweave
      ports:
        - containerPort: 55771
          protocol: TCP
      resources:
        limits:
          cpu: 0.1
          memory: 2Gi
        requests:
          cpu: 0.1
          memory: 2Gi
  nodeName: g3e1012
  nodeSelector:
    node.coreweave.cloud/class: cpu
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    - effect: NoSchedule
      key: node.coreweave.cloud/reserved
      operator: Equal
      value: 3f7b5a8be40bc71f2e0671bfc98f47c47e2a7fb5


