apiVersion: v1
kind: Pod
metadata:
  name: sps-coturn-maayaverse-67d5d9657-4pcxn
  labels:
    app.kubernetes.io/name: maayaverse
    app.kubernetes.io/version: maayaverse-v1
spec:
  containers:
    - name: sps-coturn-container
      image: coturn/coturn:4.5.2-r8
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi
      volumeMounts:
        - mountPath: /etc/coturn
          name: config-volume
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  initContainers:
    - name: sps-coturn-server-init
      image: docker.io/tensorworks/sps-coturn-init:v0.9.10-coreweave
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          value: tenant-74334f-oidev
        - name: CONFIGMAP_NAME
          value: sps-coturn-maayaverse
        - name: SPS_APPLICATION_NAME
          value: maayaverse
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  nodeName: g30c653
  nodeSelector:
    node.coreweave.cloud/class: cpu
  serviceAccount: sps-coturn
  serviceAccountName: sps-coturn
  tolerations:
    - effect: No

