apiVersion: v1
kind: Service
metadata:
  name: sps-auth-maayaverse
  namespace: tenant-74334f-oidev
spec:
  ports:
    - port: 55771
      protocol: TCP
      targetPort: 55771
  selector:
    sps.tensorworks.com.au/auth: maayaverse
  type: ClusterIP
