apiVersion: v1
kind: Service
metadata:
  name: sps-coturn-maayaverse
  namespace: tenant-74334f-oidev
spec:
  ports:
    - name: attach
      port: 1
      protocol: TCP
      targetPort: attach
  selector:
    coreweave.cloud/ignore: ignore
  type: LoadBalancer
