apiVersion: v1
kind: Service
metadata:
  name: sps-http-server-maayaverse
  namespace: tenant-74334f-oidev
spec:
  clusterIP: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    sps.tensorworks.com.au/http: maayaverse
  sessionAffinity: None
  type: ClusterIP

