apiVersion: v1
kind: Service
metadata:
  name: sps-signalling-server-maayaverse
  namespace: tenant-74334f-oidev
spec:
  # clusterIP: None
  ports:
    - name: instance-port
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: frontend-port
      port: 1025
      protocol: TCP
      targetPort: 1025
  selector:
    sps.tensorworks.com.au/ss: maayaverse
  sessionAffinity: None
  type: ClusterIP

